export enum QUERY_KEYS {
  CREATE_USER_ACCOUNT = "createUserAccount",
  GET_CURRENT_USER = "getCurrentUser",
  GET_USERS = "getUsers",
  GET_USER_BY_ID = "getUserById",
  GET_POSTS = "getPosts",
  GET_INFINITE_POSTS = "getInfinitePosts",
  GET_RECENT_POSTS = "getRecentPosts",
  GET_POST_BY_ID = "getPostById",
  GET_USER_POSTS = "getUserPosts",
  GET_FILE_PREVIEW = "getFileView",
  SEARCH_POSTS = "getSearchPosts",
  SEARCH_EXTERNAL = "searchExternal",
  GET_EXTERNAL_DETAILS = "getExternalDetails",
  GET_FOLLOWERS = "getFollowers",
  GET_FOLLOWING = "getFollowing",
  GET_REVIEWS_BY_POST = "getReviewsByPost",
  GET_REVIEWS_BY_EXTERNAL = "getReviewsByExternal",
  GET_NOTIFICATIONS = "getNotifications",
  GET_UNREAD_NOTIFICATION_COUNT = "getUnreadNotificationCount",
}
